#!/bin/sh
case "$1" in

iptables)
puppet apply /root/iptables.pp
echo "please check /etc/iptables/rules.v4 and modify it to fit your demands"
echo "To commit changes run invoke-rc.d iptables-persistent start"

;;

bind9)
puppet apply /etc/puppet/bind9.pp

;;

dhcpd)
puppet apply /etc/puppet/dhcpd.pp

;;

squid)
puppet apply /etc/puppet/squid.pp

;;

traffic)
puppet apply /etc/puppet/traffic.pp
echo "generic traffic statistics available on http://$(hostname -f)/bandwidthd/"
echo "proxy traffic statistics available on http://$(hostname -f)/lightsquid/"

;;
web)
puppet apply /etc/puppet/web.pp

;;

video)
puppet apply /etc/puppet/video.pp

;;

file)
puppet apply /etc/puppet/file.pp

;;

pdc)
puppet apply /etc/puppet/pdc.pp

;;

mail)
puppet apply /etc/puppet/mail.pp

;;

bacula)
puppet apply /etc/puppet/bacula.pp

;;

zabbix-server)
puppet apply /etc/puppet/zabbix-server.pp

;;

terminal)
puppet apply /etc/puppet/terminal.pp

;;

puppet)

;;


vg)
cat <<EOF
Sorry, but this operation is not supported yet.

To xreate xenvg, use the following scheme:

vgcreate cbs /dev/DEVICE_OF_YOUR_CHOICE
lvcreate -L 20G -n NAME cbs
mkfs.ext4 /dev/cbs/NAME
# add "/dev/cbs/NAME /MOUNTPOINT ext4 defaults 0 2"
mount /stuff 
EOF
;;
*)

echo "Usage: $0 {iptables|squid|traffic|bind9|dhcpd|web|video|file|pdc|mail|bacula|zabbix-server|terminal|puppet}"

;;

esac
