#!/bin/sh
case "$1" in

iptables)
puppet apply /root/iptables.pp
echo "please check /etc/iptables/rules.v4 and modify it to fit your demands"
echo "To commit changes run invoke-rc.d iptables-persistent start"

;;

bind9)
puppet apply /etc/puppet/bind9.pp

;;

dhcpd)
puppet apply /etc/puppet/dhcpd.pp

;;

squid)
puppet apply /etc/puppet/squid.pp

;;

traffic)
puppet apply /etc/puppet/traffic.pp
echo "generic traffic statistics available on http://$(hostname -f)/bandwidthd/"
echo "proxy traffic statistics available on http://$(hostname -f)/lightsquid/"

;;

vg)
cat <<EOF
Sorry, but this operation is not supported yet.

To xreate xenvg, use the following scheme:

vgcreate cbs /dev/DEVICE_OF_YOUR_CHOICE
lvcreate -L 20G -n NAME cbs
mkfs.ext4 /dev/cbs/NAME
# add "/dev/cbs/NAME /MOUNTPOINT ext4 defaults 0 2"
mount /stuff 
EOF
;;
*)

echo "Usage: $0 {iptables|squid|traffic|bind9|dhcpd|web|videoserver|file|pdc|mail|backup|terminal|puppet}"

;;

esac
