#!/bin/sh
case "$1" in

firewall)
puppet apply /root/firewall.pp
echo "please check /etc/iptables/rules and modify it to fit your demands"
echo "To commit changes run invoke-rc.d iptables-persistent start"

;;

bind9)
puppet apply /etc/puppet/bind9.pp

;;

dhcpd)
puppet apply /etc/puppet/dhcpd.pp

;;

traffic)
puppet apply /root/traffic.pp

;;

vg)
cat <<EOF
Sorry, but this operation is not supported yet.

To xreate xenvg, use the following scheme:

vgcreate cbs /dev/DEVICE_OF_YOUR_CHOICE
lvcreate -L 20G -n NAME cbs
mkfs.ext4 /dev/cbs/NAME
# add "/dev/cbs/NAME /MOUNTPOINT ext4 defaults 0 2"
mount /stuff 
EOF
;;
*)

echo "Usage: $0 {puppet|firewall|proxy|traffic|web|videoserver|bind9|dhcpd|file|pdc|mail|backup|terminal}"

;;

esac
